# Given a profile matrix Profile, we can evaluate the probability
# of every k-mer in a string Text and find a Profile-most probable k-mer in Text,i.e.,
# a k-mer that was most likely to have been generated by Profile among all k-mers in Text.
# For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT.
# Indeed, every other 12-mer in this string has probability 0.
#
# In general, if there are multiple Profile-most probable k-mers in Text,
# then we select the first such k-mer occurring in Text.
# Profile-most Probable k-mer Problem
# Find a Profile-most probable k-mer in a string.
#
# Given: A string Text, an integer k, and a 4 × k matrix Profile.
# Return: A Profile-most probable k-mer in Text.
# (If multiple answers exist, you may return any one.)

# Text = input()
# k = int(input())
# A = list(map(float, input().split()))
# C = list(map(float, input().split()))
# G = list(map(float, input().split()))
# T = list(map(float, input().split()))

def profile_kmer(
        Text: str,
        k: int,
        A: list[float],
        C: list[float],
        G: list[float],
        T: list[float]
) -> str:
    max_prob = -1
    max_kmer = ''

    for i in range(len(Text) - k + 1):
        kmer = Text[i : i + k] #CCGAG
        current_prob = 1

        for j in range(k):      #01234
            if kmer[j] == "A":
                current_prob = current_prob * A[j]
            elif kmer[j] == 'C':
                current_prob = current_prob * C[j]
            elif kmer[j] == 'G':
                current_prob = current_prob * G[j]
            elif kmer[j] == 'T':
                current_prob = current_prob * T[j]
        if current_prob > max_prob:
            max_prob = current_prob
            max_kmer = kmer

    return max_kmer

if __name__ == '__main__':
    Text = "ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT"
    k = 5
    A = list(map(float, "0.2 0.2 0.3 0.2 0.3".split()))
    C = list(map(float, "0.4 0.3 0.1 0.5 0.1".split()))
    G = list(map(float, "0.3 0.3 0.5 0.2 0.4".split()))
    T = list(map(float, "0.1 0.2 0.1 0.1 0.2".split()))

    print(profile_kmer(Text, k, A, C, G, T))
