#Implement Distance Between Pattern And Strings
# DistanceBetweenPatternAndStrings (Pattern, Dna)
#      k ← | Pattern |
#      расстояние ← 0
#      для каждой строки Текст в ДНК
#         HammingDistance ← ∞
#          для каждого k -мера Pattern ' в Текст
#             если  HammingDistance > HammingDistance ( Pattern , Pattern ')
#                  HammingDistance ← HammingDistance ( Pattern , Pattern ')
#          расстояние ← расстояние + HammingDistance
#     вернуть  расстояние

# Найдите расстояние между узором и набором строк.
#Find the distance between a pattern and a set of strings.
# Дано: Узор цепочки ДНК и набор цепочек ДНК ДНК.
#Given: A DNA string Pattern and a collection of DNA strings Dna.
# Возврат: DistanceBetweenPatternAndStrings ( Pattern , Dna ).
# Return: DistanceBetweenPatternAndStrings(Pattern, Dna).


def calc_hamming_distance(s1, s2):
    if len(s1) != len(s2):
        raise ValueError("Строки неодинаковой длины")
    distance = 0
    for i in range(len(s1)):
        if s1[i] != s2[i]:
            distance += 1
    return distance

def distance_between_pattern_and_strings(Pattern, Dna):
    # Вычисляет сумму минимальных расстояний Хэмминга между паттерном и всеми строками в DNA
    k = len(Pattern)
    distance = 0

    for Text in Dna:
        hamming_distance = len(Text) + 1  # ∞

        # Перебираем все k-меры в текущей строке
        for i in range(len(Text) - k + 1):
            pattern_prime = Text[i: i + k]
            current_distance = calc_hamming_distance(Pattern, pattern_prime)

            if hamming_distance > current_distance:
                hamming_distance = current_distance

        distance += hamming_distance

    return distance

if __name__ == "__main__":
    Pattern = "TCGGC"
    Dna = "GCGATTTCGTCCTCTCAGTCCTCGACCTCGGTAAATCATGAGCGCTCACGGCGGGATGATCTTAAAATGCCACGTTTGAAGGTTTGATGCGGTCTAGTCAGAACGCATCC CCGGTAGTCTGGGTAATATACTTTTGCTAACAAGTATACCTTACATCTGATTGTGATTATAAAAATCGGAATGGCCCTGAATGACACACCTGACCACCCAGGTGCCTAAT AGATTTAGCGCGTAGAAGAAGGCGATGTGAACTATTAGCTACTAACTAACCCGACTCTGAACGTTCCGAAAACATCCAGGCAAGGAAACGGTAACGGTAAGACTATGGTA CGCATTAACGGAGACCTTGAGTGGGACGGTAGTGCGGACCACACTAAATTCCCCGATTTCTTTGTGAGCCGGCGTACCCGGACGTCTCTTGCAGGATCTTCGTTATGTTG GATAACGCCTCGGCGTAGTATATGATTACCAGGCCGGCTAGGAACTTGACCTGAGTGTTACATTGCCTATTAATGCGCAACTCGAATTGATTCATTTTCTGCAATAGCCT CAATTTTGACTTCTTTCGGTGCCGTCTAGTGGTGTCCAAGGTCATCGCAGATCCGGAGCCCCCTGGCGGGTCTGCATGATTGTCGCTTCTGCAATTAGTAACAGGTTGGC TTGTCCTCTACTTATAGCCAGTGAAGACTTCCCTTAAGACTTTTAGAACAGCGGTCCTGGAAATCACTATCTTCGTTTCAAATCACGTTCCAATGTTTAAACCGGACCTT ATGAGTGATTCCACTTCGGTAAAGTTCGCCCCTACGAGTATCCAATCTCACGAGGCTCCTCGTTAGTCGTTCCGATGAACCCCGTCGTGGAAGAAACCGTTTGGGTAACC CCAAGACCCTATACACATATGAGATCCTCCAAATCCAACAGTAGGATCCTGCTGTGACAGAAGTTAGATCATGGCTTCTTCACGTCGTCCAAGCGATGGGTCACTGGTCG GACCAATGTGGCTTCTCCCTAAGTGTTTCCGTATTGGTATCCTCGGGGGTAACGAGCAGCTTTATGCAACGTGCTCTTAGGCTTGTTCCAGACTGCGTGATATGTAAAGT GTCCCCCCTTACCCTGGAGCTCTGTTACTCTGCACTGATTACCAAGCTTCACTAGAGGACTCAAGGCAACACATTATACGGCTCATTCTTATGATAATGAGTTAAAATCC ATGAAGTGGTACGTTGCAACGCTACTCTCCCACTAGGTAGGCGTTGTACACATATGCTCTGTATCTTAAAAAGGCGGTCCCGCGTAATTAGGGGTCCGCACTTTCCCTAC AGATTTCGTAACATAAGCTATGAGATGCAGTCACGGCTGGGACAGACGATACGTCATACTTAGAGGACGTCGACCGACAACCCCCGATAGTCTTGACGCTAACGCTATCG TGGCGAGGATTAGGATATCCTAGTCAGCCTAAATTATGGTAGTAATGGGTCGTGATGGATCAAGTCGTAGGCTCACCAGAGCAAGTGTTCGTATCTTTTAAGAAGCCTGA GACACCGGACATAGGGGGTCAACGCACCACCTCGCTATTGTTCGGACGCACACCCGCCCCGCTCCCAACTCAATACCGATAGCGGCGGACCGAGACAACGCTTAGGAATG TTACATGAACGTTTGTACGATTAGCGTTAGTTGCATGCCCGGGCACCCGCTCGTAGACCACTTTGTGCAGCAGATAACCAGTAATAAGAGCAATGTTCATACTGGCATAA ATAAGACACATTCTCGAGCCGAGTGTCTAGACAAGACGGAGGGGGTTTAAAAGCTAATTTTTATGTTCATGGCTACCCCCTGCAATGGGCGCATGCTTATTGATAATTAA ACCCTCGCTGAGCTTCACCTAGCTACTCTACCCATCTGAAGATGCAGATTAGCACCCGTTTGCAGAGAAACCGGAGGGCCTCTCCTTTATGTGCACGGACTCGGAGTGTT CACAGCCGAGGTCTAAGTTTAGCGTTAGCGATGGACTAACAAATTGAGCTAGACAAGCATAGGCTGCGATACGCTGATTTGAAAGAATGTGACCCCATAGAAAACCACGT TAGAGTGTCTGCTACGATGAGGGGCATCAAACTTTACCGTACGTTGCAAAGGGAGGACATGACGGCCAGCTTCGCCTTGTAGCAGTTTCCCCGCGCGCAGGCTTTGTGTT TGATTGCTGGCCAGTGATTAAATGTAGGATTTCTATAAAAAGGCGTGTAAACATGACGAGCCCACTAGTTCTGCTAAGTGAACGACGTCGAATTAGATTACGGCGATGGC TTCAATTCCAAGCCACTCCATGGTGTGTCGGTCCCGGCAGGACCGGTGTTAGCACGATGTGCATTGTGTCGAGTGTTGTAGAGCCATATCTAGTGATACAACATGGCGCG CCACGCCCGGCATTCAATAATTTGATTCTAACTCTGGCCAACAAGCCGTACCCATGATCTCACGTTCCTTTTGGATAGGCCCCCGTCGTGGATGACTGAGGCGGCGTTCC GGGTAGATGCCTCCAGTCTTCATTCTCCGAGCGTGATTTTGGCTTGGACACATTGTGTGCCATAGAGATGCTGAGCCGTTGCCGGTTTATGTAATTGATGCGTGCTCACG CGGCGTTGAGTGACCTTACGTATCTATGGGTACCGTTCCACACCTTCATTGAATGAGTCTCGGACGGCGGTACTTTTTGGCAGCGGCGTAGCCAACAGGTTTCAAGACAG TCTAGACGACTAAGGGGTAAGTTGTCTAGAGATACGATAAGCAGGATTCCGCATGACATCAAAGTTAGTAAGAGCGTGCCCACAAATCTTCACAAGAATCGTTCACCAGG GTACGACTGGAGTACCCTACAATGGCTTGCGAGTTTAATTATCACCTTATTACATGTAAGGGGTCGTAAACGGACTAGCTTTGTGTTCTCATGTGTCCGTACTTTTTGGT GCAGACCAAACGAGAACACGACAGGTTAAAGCCAGCACGAGATATCGCGGGCATGTAGTTGTCGGAGTTGACGCGAAAAGTGCCATGTAGGGATGATAGAGCGGGGAAGT ACCTATGAGCGAGCTAGAGCGCGCCGGATGCCGTACGGAATTTACTAATAGGGCGCGTAACGATTGAGGTTACAAGTGCACACCGACCATAAGCTGTTAGCCTCAGTAAG CCTATATCGGACGCGGACAACAACGGCAGTGTGAATCAACCGCGGTAGTAAGTAAGGGCTCTGCGTAGCCAGTCACTACCCATCGGCTTCTATGCGTGCGCCAGCTTCGC AATCAGGACGACACGACTCTCCTCATAACTATCAACCTCATCTGGTGTTCAGCATAGTAGGCAAGGTCGCTAGTGGTATCTACATGCTAGGTTAAGTGGAATAAGGTAGT".split()
    result = distance_between_pattern_and_strings(Pattern, Dna)
    print(result)

# with open("/Users/fixed/PycharmProjects/BioinfAlgos/Week_8/rosalind_ba2h.txt", "r") as f:
#     Pattern = f.readline().strip()
#     Dna = f.readline().strip().split("")
# result = distance_between_pattern_and_strings(Pattern, Dna)
# print(result)